# Generated by Django 4.1.1 on 2022-11-11 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_prf_image_alter_post_slug_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='PRF_image',
        ),
    ]
